server:
    port: 9080

spring:
    profiles:
        active: cloud
    data:
        mongodb:
            host: localhost
            port: 27017
            database: fhirApi

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: fhirApi

cache:
    memcached:
        ip: localhost
        port: 11211